Double quotes
kylefarris/tsqlstring pull request #1
Opened 2020-08-28 11:21 UTC by tdiam

Even though double quotes were included in `CHARS_GLOBAL_REGEXP` there was no escape mapping.
This PR resolves this issue:

```js
const tsqlstring = require('tsqlstring')

console.log(tsqlstring.escape('Sup"er'))
// before this PR: 'Supundefineder'
// after this PR: 'Sup\"er'
```

2020-09-24 14:23 UTC, samjross commented
This fix doesn't work for me personally. I tested it out locally with an mssql server, and `"\""   : '\\"',` leaves me with a backslash in the actual string on the table.

For me, `"\""   : '"',` worked.

2020-09-24 14:34 UTC, samjross commented
Seems to me that in mssql, `"` doesn't actually need to be escaped at all, so the real solution is probably to take `\"` out of `CHARS_GLOBAL_REGEXP`, but I'm not confident that I understand the purpose or scope if this library enough to test that. That's what works for me.

2020-09-24 15:20 UTC, kylefarris commented
I think I went through this same conundrum when I was originally writing this library. In T-SQL the double-quote itself can be considered a way to protect identifiers but only if the setting is turned on for the server (something this library may not be able to easily detect). In other words, escaping the double-quote could potentially break queries that already have protected identifiers and cause it to totally break.

So, like @samjross said, I think we just need to remove the `\"` from the `CHARS_GLOBAL_REGEXP` (looks like removing that was just an oversight anyway).

So, @tdiam if you just want to make that change and undo the other stuff, that'd probably fix it. I'd be happy to get this PR merged in.

2020-09-24 15:23 UTC, kylefarris requested changes

2020-09-24 15:23 UTC, kylefarris commented on lib/SqlString.js
> +            "\""   : '\\"',
```suggestion
```

2020-09-24 15:23 UTC, kylefarris commented on test/unit/test-SqlString.js
> +
```suggestion
  'double quotes do not get escaped': function() {
    assert.equal(SqlString.escape('Sup"er'), `'Sup"er'`);
    assert.equal(SqlString.escape('Super"'), `'Super"'`);
  },


```

2020-09-24 15:25 UTC, kylefarris commented
@tdiam I've updated your remote branch with some suggested edits. The only thing you need to do now is remove the double quote item from `CHARS_GLOBAL_REGEXP`.

2020-09-24 15:27 UTC, kylefarris commented
@tdiam, actually, it looks like I was able to edit your branch directly somehow? So, I'll go ahead and merge this in and up date the package on NPM.

2020-09-24 15:29 UTC, merged

2020-09-24 15:34 UTC, kylefarris commented
Patch added to NPM as v1.0.1.

2020-09-26 09:44 UTC, tdiam commented
Yep, I reached the same conclusions. Thanks @samjross, @kylefarris !

2020-09-28 16:16 UTC, samjross commented
awesome, thank you @kylefarris !

2020-09-28 16:22 UTC, samjross commented
@kylefarris I can't see a way to open an issue on this repo, but I've run into a problem with new lines, `\n`